### ISSUE TITLE
Programmed Awfully

### ISSUE THREAD

**Issue by m-masterton** [Jsanderson2005/checkmate-checker#1]
Way to bloated.
Unfortunately my computer crashes every time I run the program.

Over 1400 lines of code for something that can easily be done in 200. Clearly written with lack of skill.

Filled with bugs and an extreme lack of useful comments.

1/10
Would not recommend to a friend or enemy

**Comment by Jsanderson2005** [comment]
Thanks for your feedback,

Unfortunately, if you refer to the [Readme](https://github.com/Jsanderson2005/checkmate-checker/blob/main/README.md), it clearly tells you not to use it, therefore I will not be offering any support with the code, and call this issue closed.

It's like I didn't want this to be used in anything other than my personal use.
